title = "seed-api api config"
[Server]
port = 8001
debugMode = false
tokenDuration = 10
pid = "/app/run/seed-api.pid"
shutdownTimeOut = 3
env = "dev"

[logConfig]
errorLogPath = "/apps/logs/seed-api/error.log"
accessLogPath = "/apps/logsseed-api/access.log"
level = "DEBUG"
stdErr = true

[Database]
driver = "postgres"
host = "127.0.0.1"
port = 5432
user = "zhouyang"
password = ""
dbname = "zhouyang"

[Memcache]
cluster = []
expire = 10

[Tracer]
Enable = true
AgentHost = "127.0.0.1"
AgentPort = "6831"
ServiceName = "seedHabits"