title = "seed-api api config"
[Server]
port = 8001
debugMode = false
tokenDuration = 10
pid = "/app/run/seed-api.pid"
shutdownTimeOut = 3
env = "dev"

[logConfig]
errorLogPath = "/apps/logs/seed-api/error.log"
accessLogPath = "/apps/logsseed-api/access.log"
level = "DEBUG"
stdErr = true

[Database]
driver = "postgres"
host = "localhost"
port = 5432
user = "postgres"
password = ""
dbname = "postgres"

[Memcache]
cluster = []
expire = 10