definitions:
  dao.LoginReq:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    name: aogo
    url: localhost:8081
  description: seedHabits开发文档
  title: SeedHabits
paths:
  /api/v1/user/info/get:
    get:
      description: 查询用户信息功能
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 用户模块
  /api/v1/user/login:
    post:
      description: 用户登陆功能
      parameters:
      - description: 用户名与密码
        in: body
        name: LoginReq
        required: true
        schema:
          $ref: '#/definitions/dao.LoginReq'
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 用户模块
swagger: "2.0"
